# Generated by Django 5.0.6 on 2024-05-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finca', '0002_alter_finca_fk_id_municipio_and_more'),
        ('muestra', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='muestra',
            name='fk_id_finca',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='finca.finca'),
        ),
    ]
