# Generated by Django 5.0.4 on 2024-07-31 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='numero_documento',
            field=models.BigIntegerField(null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('Encargado', 'Encargado'), ('Invitado', 'Invitado')], default=1, max_length=21, verbose_name='Rol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tipo_documento',
            field=models.CharField(choices=[('Cedula ciudadania', 'Cedula ciudadania'), ('Tarjeta de identidad', 'Tarjeta de identidad'), ('Nit', 'Nit')], default=1, max_length=21, verbose_name='Tipo documento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
