# Generated by Django 5.0.6 on 2024-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_id_formato', models.IntegerField()),
                ('fk_id_datos', models.IntegerField()),
                ('valor', models.FloatField()),
                ('fk_id_servicios', models.IntegerField()),
            ],
        ),
    ]
