# Generated by Django 5.0.6 on 2024-05-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datos', '0002_alter_datos_fk_id_formato'),
        ('detalle', '0001_initial'),
        ('servicios', '0001_initial'),
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle',
            name='fk_id_datos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='datos.datos'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fk_id_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versiones'),
        ),
        migrations.AlterField(
            model_name='detalle',
            name='fk_id_servicios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicios.servicios'),
        ),
    ]
