# Generated by Django 5.0.6 on 2024-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Versiones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=45)),
                ('editable', models.BooleanField()),
                ('fk_id_tipo_formato', models.IntegerField()),
                ('fk_id_usuarios', models.IntegerField()),
                ('formato_vacio', models.BinaryField(null=True)),
                ('fk_documentos', models.IntegerField()),
            ],
        ),
    ]
