# Generated by Django 5.0.6 on 2024-05-22 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_alter_documentos_fk_id_usuarios'),
        ('tipo_formato', '0001_initial'),
        ('versiones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='versiones',
            name='fk_documentos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='documentos.documentos'),
        ),
        migrations.AlterField(
            model_name='versiones',
            name='fk_id_tipo_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tipo_formato.tipoformato'),
        ),
        migrations.AlterField(
            model_name='versiones',
            name='fk_id_usuarios',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
