# Generated by Django 5.0.6 on 2024-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_servicios', models.CharField(max_length=100)),
                ('fk_id_muestra', models.IntegerField()),
                ('fk_formato', models.IntegerField(null=True)),
            ],
        ),
    ]
