# Generated by Django 5.0.6 on 2024-05-22 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestra', '0002_alter_muestra_fk_id_finca'),
        ('servicios', '0001_initial'),
        ('versiones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicios',
            name='fk_formato',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='versiones.versiones'),
        ),
        migrations.AlterField(
            model_name='servicios',
            name='fk_id_muestra',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='muestra.muestra'),
        ),
    ]
