# Generated by Django 5.0.6 on 2024-05-22 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_finca', models.CharField(max_length=50)),
                ('fk_id_municipio', models.IntegerField()),
                ('fk_id_usuario', models.IntegerField()),
            ],
        ),
    ]
